export default [
  { title: "Pride and Prejudice", author: "Jane Austen", description: "From the author of When Bad Things Happen to Good People comes an inspiring new bestseller that puts human feelings of guilt and the problem of evil at center stage.", image: "http://images.amazon.com/images/P/055321215X.01.LZZZZZZZ.jpg" },
  { title: "Timeline", author: "Michael Crichton", description: "", image: "http://images.amazon.com/images/P/0345417623.01.LZZZZZZZ.jpg" },
  { title: "More Cunning Than Man", author: "Robert Hendrickson", description: "", image: "http://images.amazon.com/images/P/1575663937.01.LZZZZZZZ.jpg" },
  { title: "Purity in Death", author: "J.D. Robb", description: "", image: "http://images.amazon.com/images/P/042518630X.01.LZZZZZZZ.jpg" },
  { title: "The Joy Luck Club", author: "Amy Tan", description: "A therapist draws on world religions, music, and art to examine the connections between people.", image: "http://images.amazon.com/images/P/0804106304.01.LZZZZZZZ.jpg" },
  { title: "The Middle Stories", author: "Sheila Heti", description: "", image: "http://images.amazon.com/images/P/0887841740.01.LZZZZZZZ.jpg" },
  { title: "Tage der Unschuld", author: "Richard North Patterson", description: "", image: "http://images.amazon.com/images/P/3442446937.01.LZZZZZZZ.jpg" },
  { title: "Icebound", author: "Dean R. Koontz", description: "The bestselling author of The Road from Coorain presents an extraordinarily powerful anthology of the autobiographical.", image: "http://images.amazon.com/images/P/0553582909.01.LZZZZZZZ.jpg" },
  { title: "Prescription for Terror", author: "Sandra Levy Ceren", description: "Describes how the new information society is altering workplace nature.", image: "http://images.amazon.com/images/P/0966986105.01.LZZZZZZZ.jpg" },
  { title: "Tess of the D'Urbervilles", author: "Thomas Hardy", description: "The story of a young girl and her family’s country life in Mississippi before World War I.", image: "http://images.amazon.com/images/P/1853260053.01.LZZZZZZZ.jpg" },
  { title: "Airframe", author: "Michael Crichton", description: "It was a wonderful summer, a great memory, the kind of love everybody ought to have...", image: "http://images.amazon.com/images/P/0345402871.01.LZZZZZZZ.jpg" },
  { title: "Lonesome Dove", author: "Larry McMurtry", description: "This detailed biography concentrates on the domestic life of the monarch and his involvement in foreign affairs.", image: "http://images.amazon.com/images/P/0671623249.01.LZZZZZZZ.jpg" },
  { title: "A Great Soup (Reprise)", author: "Jack Canfield", description: "A haunting, harrowing, gloriously moving recollection of a life on the American margin...", image: "http://images.amazon.com/images/P/1558746218.01.LZZZZZZZ.jpg" },
  { title: "More Cunning Than Man (Reprise)", author: "Robert Hendrickson", description: "", image: "http://images.amazon.com/images/P/1575663937.01.LZZZZZZZ.jpg" },
  { title: "Lieux Dits", author: "Michel Tournier", description: "Readings from Scientific American on life in extreme environments.", image: "http://images.amazon.com/images/P/2070423204.01.LZZZZZZZ.jpg" },
  { title: "An Atmosphere of Eternity", author: "David Iglehart", description: "Panic Disorder and Its Treatment provides a clear and clinically relevant presentation for physicians and patients.", image: "http://images.amazon.com/images/P/0964778319.01.LZZZZZZZ.jpg" },
  { title: "Starship Troopers", author: "Robert A. Heinlein", description: "", image: "http://images.amazon.com/images/P/0441783589.01.LZZZZZZZ.jpg" },
  { title: "The Mummies of Urumchi", author: "E. J. W. Barber", description: "", image: "http://images.amazon.com/images/P/0393045218.01.LZZZZZZZ.jpg" },
  { title: "What If?: Military Historians Imagine", author: "Robert Cowley", description: "", image: "http://images.amazon.com/images/P/0425176428.01.LZZZZZZZ.jpg" },
  { title: "Our Dumb Century", author: "The Onion", description: "", image: "http://images.amazon.com/images/P/0609804618.01.LZZZZZZZ.jpg" },
  { title: "The Yawning Heights", author: "Aleksandr Zinoviev", description: "", image: "http://images.amazon.com/images/P/0394743741.01.LZZZZZZZ.jpg" },
  { title: "Beloved", author: "Toni Morrison", description: "Insight into social and political struggles in Texas...", image: "http://images.amazon.com/images/P/0452264464.01.LZZZZZZZ.jpg" },
  { title: "The Testament (Reprise)", author: "John Grisham", description: "", image: "http://images.amazon.com/images/P/0440234743.01.LZZZZZZZ.jpg" },
  { title: "The Witchfinder (Reprise)", author: "Loren D. Estleman", description: "", image: "http://images.amazon.com/images/P/1567407781.01.LZZZZZZZ.jpg" },
  { title: "New Vegetarian", author: "Celia Brooks Brown", description: "Reflections on feline care from artists and writers...", image: "http://images.amazon.com/images/P/1841721522.01.LZZZZZZZ.jpg" },
  { title: "Shabanu: Daughter of the Wind", author: "Suzanne Fisher Staples", description: "The award-winning author reveals the spiritual life of children and how to teach morality.", image: "http://images.amazon.com/images/P/0679810307.01.LZZZZZZZ.jpg" },
  { title: "The Prince", author: "Niccolo Machiavelli", description: "Famous writers contribute to this dramatic overview of political power.", image: "http://images.amazon.com/images/P/0451625889.01.LZZZZZZZ.jpg" },
  { title: "From the Corner of His Eye", author: "Dean Koontz", description: "", image: "http://images.amazon.com/images/P/0553582747.01.LZZZZZZZ.jpg" },
  { title: "I'll Be Seeing You", author: "Mary Higgins Clark", description: "", image: "http://images.amazon.com/images/P/0671888587.01.LZZZZZZZ.jpg" },
  { title: "Sturmzeit (Reprise)", author: "Charlotte Link", description: "Since its launch in 2000, the Best New American Voices series has been acclaimed for the range and originality of its selections.", image: "http://images.amazon.com/images/P/3442410665.01.LZZZZZZZ.jpg" },
  { title: "The Angel Is Near", author: "Deepak Chopra", description: "\"The chasm is where high-tech fortunes are lost... the tornado is where they are made,\"-- Steve Jobs.", image: "http://images.amazon.com/images/P/0312970242.01.LZZZZZZZ.jpg" },
  { title: "Breathing Lessons", author: "Anne Tyler", description: "Every couple experiences a restless aching to know and experience God together.", image: "http://images.amazon.com/images/P/042511774X.01.LZZZZZZZ.jpg" },
  { title: "Mary-Kate & Ashley: Switching Goals", author: "Mary-Kate & Ashley Olsen", description: "", image: "http://images.amazon.com/images/P/0061076031.01.LZZZZZZZ.jpg" },
  { title: "The Ruby in the Smoke", author: "Philip Pullman", description: "", image: "http://images.amazon.com/images/P/0394895894.01.LZZZZZZZ.jpg" },
  { title: "Lying Awake", author: "Mark Salzman", description: "Sometimes in their chanting monks will land upon a note and sing it in florid fashion, one syllable of text for fifty notes.", image: "http://images.amazon.com/images/P/0375406328.01.LZZZZZZZ.jpg" },
  { title: "Decision in Normandy", author: "Carlo D'Este", description: "", image: "http://images.amazon.com/images/P/0060973129.01.LZZZZZZZ.jpg" },
  { title: "Miss Zukas and the Raven's Dance", author: "Jo Dereske", description: "A treasury of French medieval lore combines the tales of Lancelot and Guinevere, Tristan and Isolde, Troilus and Criseyde.", image: "http://images.amazon.com/images/P/038078243X.01.LZZZZZZZ.jpg" },
  { title: "Sturmzeit", author: "Charlotte Link", description: "Since its launch in 2000, the Best New American Voices series has been acclaimed...", image: "http://images.amazon.com/images/P/3442410665.01.LZZZZZZZ.jpg" },
  { title: "Left Behind", author: "Tim Lahaye", description: "Draws on interviews and unpublished documents to re-create the life and times of the outspoken and influential labor leader.", image: "http://images.amazon.com/images/P/0842342702.01.LZZZZZZZ.jpg" },
  { title: "Isle of Dogs", author: "Patricia Cornwell", description: "", image: "http://images.amazon.com/images/P/0425182908.01.LZZZZZZZ.jpg" },
  { title: "Love, Medicine and Miracles", author: "M.D. Bernie S. Siegel", description: "", image: "http://images.amazon.com/images/P/0060914068.01.LZZZZZZZ.jpg" },
  { title: "Jane Doe (Reprise)", author: "R. J. Kaiser", description: "\"The Bible and the social and moral consequences that derive from its interpretation...\"", image: "http://images.amazon.com/images/P/1552041778.01.LZZZZZZZ.jpg" },
  { title: "Beloved (Reprise)", author: "Toni Morrison", description: "As a top aide to powerful Texas Congressman Ronald Coleman, John Jackley watched the nation's highest elected", image: "http://images.amazon.com/images/P/0452264464.01.LZZZZZZZ.jpg" },
  { title: "The Accidental Virgin", author: "Valerie Frankel", description: "The world's most beloved detective, Sherlock Holmes, travels to Minnesota for a unique case.", image: "http://images.amazon.com/images/P/0060938412.01.LZZZZZZZ.jpg" },
  { title: "The Kitchen God's Wife", author: "Amy Tan", description: "", image: "http://images.amazon.com/images/P/0399135782.01.LZZZZZZZ.jpg" },
  { title: "Getting Well Again", author: "O. Carol Simonton Md", description: "", image: "http://images.amazon.com/images/P/0553280333.01.LZZZZZZZ.jpg" },
  { title: "Hitler's Secret Bankers", author: "Adam Lebor", description: "Deadly germs sprayed in shopping malls, bomb-lets spewing anthrax spores over battlefields...", image: "http://images.amazon.com/images/P/080652121X.01.LZZZZZZZ.jpg" },
  { title: "Chocolate Jesus", author: "Stephan Jaramillo", description: "For the first time ever, veteran World War II cryptographer Hervie Haufler details how American and British codebreakers...", image: "http://images.amazon.com/images/P/0425163091.01.LZZZZZZZ.jpg" },
  { title: "The Testament", author: "John Grisham", description: "", image: "http://images.amazon.com/images/P/0440234743.01.LZZZZZZZ.jpg" },
  { title: "Nights Below Station Street", author: "David Adams Richards", description: "A humor classic, this tongue-in-cheek diet plan bases calorie counts on sexual activity and charts", image: "http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg" },
  { title: "Tage der Unschuld (Reprise)", author: "Richard North Patterson", description: "", image: "http://images.amazon.com/images/P/3442446937.01.LZZZZZZZ.jpg" },
  { title: "Goodbye to the Buttermilk Sky", author: "Julia Oliver", description: "", image: "http://images.amazon.com/images/P/1881320189.01.LZZZZZZZ.jpg" },
  { title: "A Soldier of the Great War", author: "Mark Helprin", description: "", image: "http://images.amazon.com/images/P/0380715899.01.LZZZZZZZ.jpg" },
  { title: "The Street Lawyer", author: "John Grisham", description: "A cross-section of Americans--from an embittered Miss America to Arnold Schwarzenegger, from Jesse Helms to a KKK member--is seen through the eyes of a homeless man who befriends an idealistic lawyer.", image: "http://images.amazon.com/images/P/0440225701.01.LZZZZZZZ.jpg" },
  { title: "The Middle Stories (Reprise)", author: "Sheila Heti", description: "", image: "http://images.amazon.com/images/P/0887841740.01.LZZZZZZZ.jpg" },
  { title: "The Therapeutic Touch", author: "Dolores Krieger", description: "", image: "http://images.amazon.com/images/P/067176537X.01.LZZZZZZZ.jpg" },
  { title: "Anil's Ghost", author: "Michael Ondaatje", description: "", image: "http://images.amazon.com/images/P/0375410538.01.LZZZZZZZ.jpg" },
  { title: "Where You'll Find Me", author: "Ann Beattie", description: "", image: "http://images.amazon.com/images/P/074322678X.01.LZZZZZZZ.jpg" },
  { title: "Hitler's Secret Bankers (Reprise)", author: "Adam Lebor", description: "Deadly germs sprayed in shopping malls, bomb-lets spewing anthrax spores over battlefields, tiny vials", image: "http://images.amazon.com/images/P/080652121X.01.LZZZZZZZ.jpg" },
  { title: "If I'd Known Then", author: "J. R. Parrish", description: "", image: "http://images.amazon.com/images/P/1879384493.01.LZZZZZZZ.jpg" },
  { title: "Prague", author: "Arthur Phillips", description: "", image: "http://images.amazon.com/images/P/0375759778.01.LZZZZZZZ.jpg" },
  { title: "Life's Little Instruction Book", author: "H. Jackson Brown", description: "", image: "http://images.amazon.com/images/P/1558531025.01.LZZZZZZZ.jpg" },
  { title: "Wild Animus", author: "Rich Shapero", description: "Gertz, writer for the Moonie-influenced Washington Times newspaper and a reporter with the highest right-wing credentials...", image: "http://images.amazon.com/images/P/0971880107.01.LZZZZZZZ.jpg" },
  { title: "A Second Chicken Soup for the Soul", author: "Jack Canfield", description: "This haunting, harrowing, gloriously moving recollection of a life on the American margin is the story of Rick", image: "http://images.amazon.com/images/P/1558746218.01.LZZZZZZZ.jpg" },
  { title: "Proxies", author: "Laura J. Mixon", description: "", image: "http://images.amazon.com/images/P/0812523873.01.LZZZZZZZ.jpg" },
  { title: "Pigs in Heaven", author: "Barbara Kingsolver", description: "A contemporary city faces turmoil and devastation until it is visited by the serene figure of Joshua, who presents an urgent challenge.", image: "http://images.amazon.com/images/P/0060168013.01.LZZZZZZZ.jpg" },
  { title: "Pacific Northwest", author: "Hans Johannes Hoefer", description: "On December 16, 1994, a bloodletting took place in the stylish sixth-floor boardroom at Saatchi & Saatchi Company PLC headquarters in London.", image: "http://images.amazon.com/images/P/0245542957.01.LZZZZZZZ.jpg" },
  { title: "The Tao of Pooh", author: "Benjamin Hoff", description: "Explains Taoism through the adventures of Winnie the Pooh.", image: "http://images.amazon.com/images/P/0140067477.01.LZZZZZZZ.jpg" },
  { title: "The Witchfinder", author: "Loren D. Estleman", description: "", image: "http://images.amazon.com/images/P/1567407781.01.LZZZZZZZ.jpg" },
  { title: "Seabiscuit (Reprise)", author: "Laura Hillenbrand", description: "Describes how decentralization and entrepreneurship can revitalize government.", image: "http://images.amazon.com/images/P/0345465083.01.LZZZZZZZ.jpg" },
  { title: "All the King's Men", author: "Robert Penn Warren", description: "Even if you know Sandra Bernhard as an actress, singer, comedian, and performer, you're in for quite a shock with this new book.", image: "http://images.amazon.com/images/P/0156047624.01.LZZZZZZZ.jpg" },
  { title: "The Adventures of Drew and Ellie", author: "Charles Noland", description: "Expert advice on new babies from the likes of Dr. Spock and Dr. Brazleton.", image: "http://images.amazon.com/images/P/1414035004.01.LZZZZZZZ.jpg" },
  { title: "This Year It Will Be Different", author: "Maeve Binchy", description: "", image: "http://images.amazon.com/images/P/0440223571.01.LZZZZZZZ.jpg" },
  { title: "Pleading Guilty", author: "Scott Turow", description: "Collects poems written by the eleven-year-old muscular dystrophy patient, sharing his feelings and", image: "http://images.amazon.com/images/P/0671870432.01.LZZZZZZZ.jpg" },
  { title: "Wie Barney es sieht", author: "Mordecai Richler", description: "", image: "http://images.amazon.com/images/P/3404921038.01.LZZZZZZZ.jpg" },
  { title: "Black Beauty", author: "Anna Sewell", description: "", image: "http://images.amazon.com/images/P/1569871213.01.LZZZZZZZ.jpg" },
  { title: "The Dragons of Eden", author: "Carl Sagan", description: "", image: "http://images.amazon.com/images/P/0345260317.01.LZZZZZZZ.jpg" },
  { title: "Clara Callan", author: "Richard Bruce Wright", description: "", image: "http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg" },
  { title: "Out of the Silent Planet", author: "C.S. Lewis", description: "", image: "http://images.amazon.com/images/P/0684823802.01.LZZZZZZZ.jpg" },
  { title: "Seabiscuit: An American Legend", author: "Laura Hillenbrand", description: "Follows a thirtyish graduate who unexpectedly finds herself helping a celebrity biographer research the life of the champion racehorse.", image: "http://images.amazon.com/images/P/0449005615.01.LZZZZZZZ.jpg" },
  { title: "Flood: Mississippi 1927", author: "Kathleen Duey", description: "", image: "http://images.amazon.com/images/P/0689821166.01.LZZZZZZZ.jpg" },
  { title: "Under the Black Flag", author: "David Cordingly", description: "The Russian author offers an affectionate chronicle of life in the United States, with discussions", image: "http://images.amazon.com/images/P/0679425608.01.LZZZZZZZ.jpg" },
  { title: "To Kill a Mockingbird", author: "Harper Lee", description: "", image: "http://images.amazon.com/images/P/0446310786.01.LZZZZZZZ.jpg" },
  { title: "Northwest Wines and Wineries", author: "Chuck Hill", description: "", image: "http://images.amazon.com/images/P/0961769947.01.LZZZZZZZ.jpg" },
  { title: "Modern Manners", author: "P.J. O'Rourke", description: "", image: "http://images.amazon.com/images/P/087113375X.01.LZZZZZZZ.jpg" },
  { title: "Heart of Darkness", author: "Joseph Conrad", description: "", image: "http://images.amazon.com/images/P/1853262404.01.LZZZZZZZ.jpg" },
  { title: "Turning Thirty", author: "Mike Gayle", description: "", image: "http://images.amazon.com/images/P/0340767936.01.LZZZZZZZ.jpg" },
  { title: "Jane Doe", author: "R. J. Kaiser", description: "\"The Bible and the social and moral consequences that derive from its interpretation are all too important", image: "http://images.amazon.com/images/P/1552041778.01.LZZZZZZZ.jpg" },
  { title: "Tell Me This Isn't Happening", author: "Robynn Clairday", description: "", image: "http://images.amazon.com/images/P/0439095026.01.LZZZZZZZ.jpg" },
  { title: "Decipher", author: "Stel Pavlou", description: "", image: "http://images.amazon.com/images/P/0743403843.01.LZZZZZZZ.jpg" },
  { title: "Classical Mythology", author: "Mark P. O. Morford", description: "", image: "http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg" },
  { title: "Flu: The Great Influenza Pandemic", author: "Gina Bari Kolata", description: "", image: "http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg" },
  { title: "Haveli", author: "Suzanne Fisher Staples", description: "", image: "http://images.amazon.com/images/P/0679865691.01.LZZZZZZZ.jpg" },
  { title: "Der Fluch der Kaiserin", author: "Eleanor Cooney", description: "", image: "http://images.amazon.com/images/P/3442353866.01.LZZZZZZZ.jpg" },
  { title: "Goodbye to the Buttermilk Sky (Reprise)", author: "Julia Oliver", description: "", image: "http://images.amazon.com/images/P/1881320189.01.LZZZZZZZ.jpg" },
  { title: "Downtown", author: "Anne Rivers Siddons", description: "", image: "http://images.amazon.com/images/P/0061099686.01.LZZZZZZZ.jpg" }
];